# Form implementation generated from reading ui file 'Pms_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 750)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uninstallBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uninstallBtn.setGeometry(QtCore.QRect(40, 50, 91, 41))
        self.uninstallBtn.setObjectName("uninstallBtn")
        self.installBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.installBtn.setGeometry(QtCore.QRect(160, 50, 91, 41))
        self.installBtn.setObjectName("installBtn")
        self.stopBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(410, 50, 91, 41))
        self.stopBtn.setObjectName("stopBtn")
        self.tableResult = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableResult.setGeometry(QtCore.QRect(40, 140, 461, 581))
        self.tableResult.setObjectName("tableResult")
        self.reloadBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reloadBtn.setGeometry(QtCore.QRect(290, 50, 91, 41))
        self.reloadBtn.setObjectName("reloadBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System Power Management Uninstall/ Install App"))
        self.uninstallBtn.setText(_translate("MainWindow", "Uninstall"))
        self.installBtn.setText(_translate("MainWindow", "Install"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.reloadBtn.setText(_translate("MainWindow", "Reload"))
